theme = "onedarker_transparent"

[editor]
color-modes = true
auto-pairs = true
#auto-format = false
auto-format = true
line-number = "relative"
rulers = [78]
trim-final-newlines = true
trim-trailing-whitespace = true
cursorline = true
default-yank-register = "+"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "version-control", "file-name"]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
# evil-helix only
character = "▏"  # "❘" "▏", "┆", "┊", "⸽" "╎"
rainbow-option = "dim"

# [editor.whitespace]
# render = "all"

# [editor.lsp]
# auto-signature-help = false
# display-messages = true

[keys.normal]
"%" = "select_all"
"D" = "@d$"
